url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "Pig Place"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"